
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thescorchedwastelands.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.thescorchedwastelands.block.WreckedventBlock;
import net.mcreator.thescorchedwastelands.block.WreckedvendingmachineBlock;
import net.mcreator.thescorchedwastelands.block.WreckedcrateBlock;
import net.mcreator.thescorchedwastelands.block.WreckedcontrolpanelBlock;
import net.mcreator.thescorchedwastelands.block.WreckedconsoleBlock;
import net.mcreator.thescorchedwastelands.block.WreckedTVBlock;
import net.mcreator.thescorchedwastelands.block.WideventBlock;
import net.mcreator.thescorchedwastelands.block.UtilitypoleBlock;
import net.mcreator.thescorchedwastelands.block.TrashcanBlock;
import net.mcreator.thescorchedwastelands.block.ToxicwastebarrelBlock;
import net.mcreator.thescorchedwastelands.block.TestdimensionPortalBlock;
import net.mcreator.thescorchedwastelands.block.SuppliesShelfBlock;
import net.mcreator.thescorchedwastelands.block.SmashedscreenBlock;
import net.mcreator.thescorchedwastelands.block.SmallventBlock;
import net.mcreator.thescorchedwastelands.block.SmallrustedcrateBlock;
import net.mcreator.thescorchedwastelands.block.SlopedrustpanelBlock;
import net.mcreator.thescorchedwastelands.block.SleekdarkpanelBlock;
import net.mcreator.thescorchedwastelands.block.SignTopBlock;
import net.mcreator.thescorchedwastelands.block.SignPoleBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedtapummeBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedplatingBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedhazardtapeBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedgrassBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedcargoplatingBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedDebrisBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedBushBlock;
import net.mcreator.thescorchedwastelands.block.ScorchedBenchBlock;
import net.mcreator.thescorchedwastelands.block.RustywallBlock;
import net.mcreator.thescorchedwastelands.block.RustytechBlock;
import net.mcreator.thescorchedwastelands.block.RustyscafoldingBlock;
import net.mcreator.thescorchedwastelands.block.RustymetalslabBlock;
import net.mcreator.thescorchedwastelands.block.RustymetalplaquestairsBlock;
import net.mcreator.thescorchedwastelands.block.RustymetalplaqueslabBlock;
import net.mcreator.thescorchedwastelands.block.RustymetalplaquesBlock;
import net.mcreator.thescorchedwastelands.block.RustymetalBlock;
import net.mcreator.thescorchedwastelands.block.RustygrateBlock;
import net.mcreator.thescorchedwastelands.block.RustydoublecabinetBlock;
import net.mcreator.thescorchedwastelands.block.RustycabinetBlock;
import net.mcreator.thescorchedwastelands.block.RustyboltedplatesBlock;
import net.mcreator.thescorchedwastelands.block.RustyLockerBlock;
import net.mcreator.thescorchedwastelands.block.RustedwatertankBlock;
import net.mcreator.thescorchedwastelands.block.RustedplatesBlock;
import net.mcreator.thescorchedwastelands.block.RustedoilbarrelBlock;
import net.mcreator.thescorchedwastelands.block.RustedcrateBlock;
import net.mcreator.thescorchedwastelands.block.RustedchairBlock;
import net.mcreator.thescorchedwastelands.block.RustedchainlinkfenceBlock;
import net.mcreator.thescorchedwastelands.block.RustedboilerBlock;
import net.mcreator.thescorchedwastelands.block.RustedbarsBlock;
import net.mcreator.thescorchedwastelands.block.RustedTableBlock;
import net.mcreator.thescorchedwastelands.block.RustedBrokenFanBlock;
import net.mcreator.thescorchedwastelands.block.RoughstoneBlock;
import net.mcreator.thescorchedwastelands.block.RivetrustyplatingBlock;
import net.mcreator.thescorchedwastelands.block.RivetlessrustypanelBlock;
import net.mcreator.thescorchedwastelands.block.RedDrySandBlock;
import net.mcreator.thescorchedwastelands.block.PoletopBlock;
import net.mcreator.thescorchedwastelands.block.PlatedmetalslabBlock;
import net.mcreator.thescorchedwastelands.block.PlatedmetalBlock;
import net.mcreator.thescorchedwastelands.block.PipefenceBlock;
import net.mcreator.thescorchedwastelands.block.PapersBlock;
import net.mcreator.thescorchedwastelands.block.OldpapersBlock;
import net.mcreator.thescorchedwastelands.block.Oldpapers3Block;
import net.mcreator.thescorchedwastelands.block.Oldpapers2Block;
import net.mcreator.thescorchedwastelands.block.Oldpapers1Block;
import net.mcreator.thescorchedwastelands.block.OldglasspaneBlock;
import net.mcreator.thescorchedwastelands.block.OldglassBlock;
import net.mcreator.thescorchedwastelands.block.OlddebrisBlock;
import net.mcreator.thescorchedwastelands.block.OldbedBlock;
import net.mcreator.thescorchedwastelands.block.MetalsheetsBlock;
import net.mcreator.thescorchedwastelands.block.MetalplaquestairsBlock;
import net.mcreator.thescorchedwastelands.block.MetalplaqueslabBlock;
import net.mcreator.thescorchedwastelands.block.MetalplaquesBlock;
import net.mcreator.thescorchedwastelands.block.MetaliccolumnBlock;
import net.mcreator.thescorchedwastelands.block.MakeshiftmetalsheetsBlock;
import net.mcreator.thescorchedwastelands.block.LittletableBlock;
import net.mcreator.thescorchedwastelands.block.JunktechBlock;
import net.mcreator.thescorchedwastelands.block.JunkpileBlock;
import net.mcreator.thescorchedwastelands.block.IronframesBlock;
import net.mcreator.thescorchedwastelands.block.HorizontalwreckedventBlock;
import net.mcreator.thescorchedwastelands.block.HangingwiresBlock;
import net.mcreator.thescorchedwastelands.block.GrayplatedmetalBlock;
import net.mcreator.thescorchedwastelands.block.ErodedmetalpanelsBlock;
import net.mcreator.thescorchedwastelands.block.DustywoodBlock;
import net.mcreator.thescorchedwastelands.block.DustywireboxBlock;
import net.mcreator.thescorchedwastelands.block.DustygrateBlock;
import net.mcreator.thescorchedwastelands.block.DustycircuitBlock;
import net.mcreator.thescorchedwastelands.block.DumpsterBlock;
import net.mcreator.thescorchedwastelands.block.DryrockBlock;
import net.mcreator.thescorchedwastelands.block.DrydirtBlock;
import net.mcreator.thescorchedwastelands.block.DiagonalwreckedventBlock;
import net.mcreator.thescorchedwastelands.block.DecayedshelfBlock;
import net.mcreator.thescorchedwastelands.block.DebrisslabBlock;
import net.mcreator.thescorchedwastelands.block.DarkglasspaneBlock;
import net.mcreator.thescorchedwastelands.block.DarkglassBlock;
import net.mcreator.thescorchedwastelands.block.CopperrebbarBlock;
import net.mcreator.thescorchedwastelands.block.CharredmetalplatingBlock;
import net.mcreator.thescorchedwastelands.block.CharredmetalplatesBlock;
import net.mcreator.thescorchedwastelands.block.ChainlinkfenceBlock;
import net.mcreator.thescorchedwastelands.block.BrokenwoodenchairBlock;
import net.mcreator.thescorchedwastelands.block.BrokentrafficpoleBlock;
import net.mcreator.thescorchedwastelands.block.BrokentrafficlightsBlock;
import net.mcreator.thescorchedwastelands.block.BrokenterminalBlock;
import net.mcreator.thescorchedwastelands.block.BrokentelevisionsetBlock;
import net.mcreator.thescorchedwastelands.block.BrokentableBlock;
import net.mcreator.thescorchedwastelands.block.BrokensmalldrawerBlock;
import net.mcreator.thescorchedwastelands.block.BrokenregisterBlock;
import net.mcreator.thescorchedwastelands.block.BrokenradiocabinetBlock;
import net.mcreator.thescorchedwastelands.block.BrokenfridgeBlock;
import net.mcreator.thescorchedwastelands.block.BrokencounterBlock;
import net.mcreator.thescorchedwastelands.block.BrockeneletricboxBlock;
import net.mcreator.thescorchedwastelands.block.BigbrokendrawerBlock;
import net.mcreator.thescorchedwastelands.block.BarSupportBlock;
import net.mcreator.thescorchedwastelands.block.AlsphalfblockBlock;
import net.mcreator.thescorchedwastelands.TheScorchedWastelandsMod;

public class TheScorchedWastelandsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TheScorchedWastelandsMod.MODID);
	public static final RegistryObject<Block> JUNKPILE = REGISTRY.register("junkpile", () -> new JunkpileBlock());
	public static final RegistryObject<Block> SCORCHEDJUNK = REGISTRY.register("scorchedjunk", () -> new ScorchedgrassBlock());
	public static final RegistryObject<Block> SCORCHED_DEBRIS = REGISTRY.register("scorched_debris", () -> new ScorchedDebrisBlock());
	public static final RegistryObject<Block> SCORCHED_BUSH = REGISTRY.register("scorched_bush", () -> new ScorchedBushBlock());
	public static final RegistryObject<Block> RED_DRY_SAND = REGISTRY.register("red_dry_sand", () -> new RedDrySandBlock());
	public static final RegistryObject<Block> DRYROCK = REGISTRY.register("dryrock", () -> new DryrockBlock());
	public static final RegistryObject<Block> DUSTYWOOD = REGISTRY.register("dustywood", () -> new DustywoodBlock());
	public static final RegistryObject<Block> POLETOP = REGISTRY.register("poletop", () -> new PoletopBlock());
	public static final RegistryObject<Block> UTILITYPOLE = REGISTRY.register("utilitypole", () -> new UtilitypoleBlock());
	public static final RegistryObject<Block> DRYDIRT = REGISTRY.register("drydirt", () -> new DrydirtBlock());
	public static final RegistryObject<Block> OLDDEBRIS = REGISTRY.register("olddebris", () -> new OlddebrisBlock());
	public static final RegistryObject<Block> RUSTEDCRATE = REGISTRY.register("rustedcrate", () -> new RustedcrateBlock());
	public static final RegistryObject<Block> SMALLRUSTEDCRATE = REGISTRY.register("smallrustedcrate", () -> new SmallrustedcrateBlock());
	public static final RegistryObject<Block> DEBRISSLAB = REGISTRY.register("debrisslab", () -> new DebrisslabBlock());
	public static final RegistryObject<Block> RUSTYMETAL = REGISTRY.register("rustymetal", () -> new RustymetalBlock());
	public static final RegistryObject<Block> PLATEDMETAL = REGISTRY.register("platedmetal", () -> new PlatedmetalBlock());
	public static final RegistryObject<Block> COPPERREBBAR = REGISTRY.register("copperrebbar", () -> new CopperrebbarBlock());
	public static final RegistryObject<Block> PLATEDMETALSLAB = REGISTRY.register("platedmetalslab", () -> new PlatedmetalslabBlock());
	public static final RegistryObject<Block> RUSTYMETALSLAB = REGISTRY.register("rustymetalslab", () -> new RustymetalslabBlock());
	public static final RegistryObject<Block> TESTDIMENSION_PORTAL = REGISTRY.register("testdimension_portal", () -> new TestdimensionPortalBlock());
	public static final RegistryObject<Block> IRONFRAMES = REGISTRY.register("ironframes", () -> new IronframesBlock());
	public static final RegistryObject<Block> SIGN_POLE = REGISTRY.register("sign_pole", () -> new SignPoleBlock());
	public static final RegistryObject<Block> SIGN_TOP = REGISTRY.register("sign_top", () -> new SignTopBlock());
	public static final RegistryObject<Block> BAR_SUPPORT = REGISTRY.register("bar_support", () -> new BarSupportBlock());
	public static final RegistryObject<Block> SCORCHED_BENCH = REGISTRY.register("scorched_bench", () -> new ScorchedBenchBlock());
	public static final RegistryObject<Block> DUMPSTER = REGISTRY.register("dumpster", () -> new DumpsterBlock());
	public static final RegistryObject<Block> BROCKENELETRICBOX = REGISTRY.register("brockeneletricbox", () -> new BrockeneletricboxBlock());
	public static final RegistryObject<Block> SUPPLIES_SHELF = REGISTRY.register("supplies_shelf", () -> new SuppliesShelfBlock());
	public static final RegistryObject<Block> WRECKEDVENT = REGISTRY.register("wreckedvent", () -> new WreckedventBlock());
	public static final RegistryObject<Block> WRECKEDVENDINGMACHINE = REGISTRY.register("wreckedvendingmachine", () -> new WreckedvendingmachineBlock());
	public static final RegistryObject<Block> WRECKED_TV = REGISTRY.register("wrecked_tv", () -> new WreckedTVBlock());
	public static final RegistryObject<Block> RUSTED_TABLE = REGISTRY.register("rusted_table", () -> new RustedTableBlock());
	public static final RegistryObject<Block> HANGINGWIRES = REGISTRY.register("hangingwires", () -> new HangingwiresBlock());
	public static final RegistryObject<Block> LITTLETABLE = REGISTRY.register("littletable", () -> new LittletableBlock());
	public static final RegistryObject<Block> SMASHEDSCREEN = REGISTRY.register("smashedscreen", () -> new SmashedscreenBlock());
	public static final RegistryObject<Block> RUSTY_LOCKER = REGISTRY.register("rusty_locker", () -> new RustyLockerBlock());
	public static final RegistryObject<Block> RUSTED_BROKEN_FAN = REGISTRY.register("rusted_broken_fan", () -> new RustedBrokenFanBlock());
	public static final RegistryObject<Block> WRECKEDCRATE = REGISTRY.register("wreckedcrate", () -> new WreckedcrateBlock());
	public static final RegistryObject<Block> BROKENTERMINAL = REGISTRY.register("brokenterminal", () -> new BrokenterminalBlock());
	public static final RegistryObject<Block> WRECKEDCONSOLE = REGISTRY.register("wreckedconsole", () -> new WreckedconsoleBlock());
	public static final RegistryObject<Block> WRECKEDCONTROLPANEL = REGISTRY.register("wreckedcontrolpanel", () -> new WreckedcontrolpanelBlock());
	public static final RegistryObject<Block> RUSTEDCHAIR = REGISTRY.register("rustedchair", () -> new RustedchairBlock());
	public static final RegistryObject<Block> RUSTEDBOILER = REGISTRY.register("rustedboiler", () -> new RustedboilerBlock());
	public static final RegistryObject<Block> BROKENTABLE = REGISTRY.register("brokentable", () -> new BrokentableBlock());
	public static final RegistryObject<Block> DECAYEDSHELF = REGISTRY.register("decayedshelf", () -> new DecayedshelfBlock());
	public static final RegistryObject<Block> BROKENREGISTER = REGISTRY.register("brokenregister", () -> new BrokenregisterBlock());
	public static final RegistryObject<Block> GRAYPLATEDMETAL = REGISTRY.register("grayplatedmetal", () -> new GrayplatedmetalBlock());
	public static final RegistryObject<Block> CHARREDMETALPLATING = REGISTRY.register("charredmetalplating", () -> new CharredmetalplatingBlock());
	public static final RegistryObject<Block> DUSTYGRATE = REGISTRY.register("dustygrate", () -> new DustygrateBlock());
	public static final RegistryObject<Block> SCORCHEDPLATING = REGISTRY.register("scorchedplating", () -> new ScorchedplatingBlock());
	public static final RegistryObject<Block> RUSTYSCAFOLDING = REGISTRY.register("rustyscafolding", () -> new RustyscafoldingBlock());
	public static final RegistryObject<Block> DUSTYCIRCUIT = REGISTRY.register("dustycircuit", () -> new DustycircuitBlock());
	public static final RegistryObject<Block> RUSTYBOLTEDPLATES = REGISTRY.register("rustyboltedplates", () -> new RustyboltedplatesBlock());
	public static final RegistryObject<Block> RUSTEDBARS = REGISTRY.register("rustedbars", () -> new RustedbarsBlock());
	public static final RegistryObject<Block> RUSTEDPLATES = REGISTRY.register("rustedplates", () -> new RustedplatesBlock());
	public static final RegistryObject<Block> METALSHEETS = REGISTRY.register("metalsheets", () -> new MetalsheetsBlock());
	public static final RegistryObject<Block> SCORCHEDHAZARDTAPE = REGISTRY.register("scorchedhazardtape", () -> new ScorchedhazardtapeBlock());
	public static final RegistryObject<Block> SCORCHEDTAPUMME = REGISTRY.register("scorchedtapumme", () -> new ScorchedtapummeBlock());
	public static final RegistryObject<Block> MAKESHIFTMETALSHEETS = REGISTRY.register("makeshiftmetalsheets", () -> new MakeshiftmetalsheetsBlock());
	public static final RegistryObject<Block> METALICCOLUMN = REGISTRY.register("metaliccolumn", () -> new MetaliccolumnBlock());
	public static final RegistryObject<Block> SCORCHEDCARGOPLATING = REGISTRY.register("scorchedcargoplating", () -> new ScorchedcargoplatingBlock());
	public static final RegistryObject<Block> SLOPEDRUSTPANEL = REGISTRY.register("slopedrustpanel", () -> new SlopedrustpanelBlock());
	public static final RegistryObject<Block> RUSTYTECH = REGISTRY.register("rustytech", () -> new RustytechBlock());
	public static final RegistryObject<Block> METALPLAQUES = REGISTRY.register("metalplaques", () -> new MetalplaquesBlock());
	public static final RegistryObject<Block> RUSTYMETALPLAQUES = REGISTRY.register("rustymetalplaques", () -> new RustymetalplaquesBlock());
	public static final RegistryObject<Block> METALPLAQUESLAB = REGISTRY.register("metalplaqueslab", () -> new MetalplaqueslabBlock());
	public static final RegistryObject<Block> RUSTYMETALPLAQUESLAB = REGISTRY.register("rustymetalplaqueslab", () -> new RustymetalplaqueslabBlock());
	public static final RegistryObject<Block> METALPLAQUESTAIRS = REGISTRY.register("metalplaquestairs", () -> new MetalplaquestairsBlock());
	public static final RegistryObject<Block> RUSTYMETALPLAQUESTAIRS = REGISTRY.register("rustymetalplaquestairs", () -> new RustymetalplaquestairsBlock());
	public static final RegistryObject<Block> RUSTYWALL = REGISTRY.register("rustywall", () -> new RustywallBlock());
	public static final RegistryObject<Block> OLDGLASSPANE = REGISTRY.register("oldglasspane", () -> new OldglasspaneBlock());
	public static final RegistryObject<Block> OLDGLASS = REGISTRY.register("oldglass", () -> new OldglassBlock());
	public static final RegistryObject<Block> DARKGLASS = REGISTRY.register("darkglass", () -> new DarkglassBlock());
	public static final RegistryObject<Block> DARKGLASSPANE = REGISTRY.register("darkglasspane", () -> new DarkglasspaneBlock());
	public static final RegistryObject<Block> CHARREDMETALPLATES = REGISTRY.register("charredmetalplates", () -> new CharredmetalplatesBlock());
	public static final RegistryObject<Block> CHAINLINKFENCE = REGISTRY.register("chainlinkfence", () -> new ChainlinkfenceBlock());
	public static final RegistryObject<Block> RUSTEDCHAINLINKFENCE = REGISTRY.register("rustedchainlinkfence", () -> new RustedchainlinkfenceBlock());
	public static final RegistryObject<Block> ERODEDMETALPANELS = REGISTRY.register("erodedmetalpanels", () -> new ErodedmetalpanelsBlock());
	public static final RegistryObject<Block> BROKENFRIDGE = REGISTRY.register("brokenfridge", () -> new BrokenfridgeBlock());
	public static final RegistryObject<Block> DUSTYWIREBOX = REGISTRY.register("dustywirebox", () -> new DustywireboxBlock());
	public static final RegistryObject<Block> BROKENSMALLDRAWER = REGISTRY.register("brokensmalldrawer", () -> new BrokensmalldrawerBlock());
	public static final RegistryObject<Block> BROKENTELEVISIONSET = REGISTRY.register("brokentelevisionset", () -> new BrokentelevisionsetBlock());
	public static final RegistryObject<Block> BIGBROKENDRAWER = REGISTRY.register("bigbrokendrawer", () -> new BigbrokendrawerBlock());
	public static final RegistryObject<Block> BROKENCOUNTER = REGISTRY.register("brokencounter", () -> new BrokencounterBlock());
	public static final RegistryObject<Block> BROKENTRAFFICPOLE = REGISTRY.register("brokentrafficpole", () -> new BrokentrafficpoleBlock());
	public static final RegistryObject<Block> BROKENTRAFFICLIGHTS = REGISTRY.register("brokentrafficlights", () -> new BrokentrafficlightsBlock());
	public static final RegistryObject<Block> SMALLVENT = REGISTRY.register("smallvent", () -> new SmallventBlock());
	public static final RegistryObject<Block> HORIZONTALWRECKEDVENT = REGISTRY.register("horizontalwreckedvent", () -> new HorizontalwreckedventBlock());
	public static final RegistryObject<Block> DIAGONALWRECKEDVENT = REGISTRY.register("diagonalwreckedvent", () -> new DiagonalwreckedventBlock());
	public static final RegistryObject<Block> TOXICWASTEBARREL = REGISTRY.register("toxicwastebarrel", () -> new ToxicwastebarrelBlock());
	public static final RegistryObject<Block> TRASHCAN = REGISTRY.register("trashcan", () -> new TrashcanBlock());
	public static final RegistryObject<Block> OLDBED = REGISTRY.register("oldbed", () -> new OldbedBlock());
	public static final RegistryObject<Block> RUSTYCABINET = REGISTRY.register("rustycabinet", () -> new RustycabinetBlock());
	public static final RegistryObject<Block> RUSTYDOUBLECABINET = REGISTRY.register("rustydoublecabinet", () -> new RustydoublecabinetBlock());
	public static final RegistryObject<Block> RUSTEDOILBARREL = REGISTRY.register("rustedoilbarrel", () -> new RustedoilbarrelBlock());
	public static final RegistryObject<Block> BROKENRADIOCABINET = REGISTRY.register("brokenradiocabinet", () -> new BrokenradiocabinetBlock());
	public static final RegistryObject<Block> RUSTEDWATERTANK = REGISTRY.register("rustedwatertank", () -> new RustedwatertankBlock());
	public static final RegistryObject<Block> ALSPHALFBLOCK = REGISTRY.register("alsphalfblock", () -> new AlsphalfblockBlock());
	public static final RegistryObject<Block> OLDPAPERS = REGISTRY.register("oldpapers", () -> new OldpapersBlock());
	public static final RegistryObject<Block> PAPERS = REGISTRY.register("papers", () -> new PapersBlock());
	public static final RegistryObject<Block> OLDPAPERS_3 = REGISTRY.register("oldpapers_3", () -> new Oldpapers3Block());
	public static final RegistryObject<Block> OLDPAPERS_2 = REGISTRY.register("oldpapers_2", () -> new Oldpapers2Block());
	public static final RegistryObject<Block> OLDPAPERS_1 = REGISTRY.register("oldpapers_1", () -> new Oldpapers1Block());
	public static final RegistryObject<Block> JUNKTECH = REGISTRY.register("junktech", () -> new JunktechBlock());
	public static final RegistryObject<Block> ROUGHSTONE = REGISTRY.register("roughstone", () -> new RoughstoneBlock());
	public static final RegistryObject<Block> SLEEKDARKPANEL = REGISTRY.register("sleekdarkpanel", () -> new SleekdarkpanelBlock());
	public static final RegistryObject<Block> PIPEFENCE = REGISTRY.register("pipefence", () -> new PipefenceBlock());
	public static final RegistryObject<Block> BROKENWOODENCHAIR = REGISTRY.register("brokenwoodenchair", () -> new BrokenwoodenchairBlock());
	public static final RegistryObject<Block> WIDEVENT = REGISTRY.register("widevent", () -> new WideventBlock());
	public static final RegistryObject<Block> RIVETLESSRUSTYPANEL = REGISTRY.register("rivetlessrustypanel", () -> new RivetlessrustypanelBlock());
	public static final RegistryObject<Block> RIVETRUSTYPLATING = REGISTRY.register("rivetrustyplating", () -> new RivetrustyplatingBlock());
	public static final RegistryObject<Block> RUSTYGRATE = REGISTRY.register("rustygrate", () -> new RustygrateBlock());
}
